on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts-alpine3.13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run the tests
      run: npm test
    - name: Build
      run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: melkio/react-to-docker:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.CONTAINER_REGISTRY_TOKEN }}
